version: '3.8'

networks:
  shared:
    external: true

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true
    networks:
      - shared
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tiktok_clone_python_development
    env_file:
      - .env
